### ISSUE TITLE
Mise en place cahier de charge chama

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#14]
Chama web app
1. Introduction
   Chama est une web application qui s'est donné pour but de résoudre un problème assez commun au association estudiantine, l'opportunité de mieux communique via une solution tout faite, fiable et facile d'usage. Elle se veut paramétrable et générique et couvrant les fonctionnalités essentielles, avec des coûts minimes.

2. Objectifs du projet

    Objectif principal : Faciliter la gestion des associations étudiantes camerounaises via un site web.
    Objectifs spécifiques :
        Gestion d'utilisateurs (inscription, profil, droits d'accès).
        Gestion d'événements (création, modification, inscription, archivage).
        Système de publication (annonces, nouvelles, articles).
        Personnalisation par l'association (logo, description, contact, galerie).

3. Exigences fonctionnelles

    Utilisateurs :
        Types d'utilisateurs (administrateur, membre de l'association, visiteur).
        Fonctionnalités par type d'utilisateur.
    Événements :
        Interface pour ajouter/modifier/supprimer des événements.
        Calendrier des événements.
    Publications et archives :
        Système de gestion de contenu pour les articles et les annonces.
        Archivage des contenus anciens accessibles.
    Configuration et personnalisation :
        Interface pour modifier le logo, la description de l’association.
        Configuration des informations de contact.

4. Exigences non fonctionnelles

    Performance : Temps de réponse du serveur, capacité de charge acceptable.
    Sécurité : Gestion des accès, protection des données.
    Compatibilité : Support des différents navigateurs et appareils.
    Accessibilité : Conformité aux standards d'accessibilité web et responsive.

5. Technologies à utiliser

    Frontend : React, Angular ou Vue.js pour les interfaces dynamiques.
    Backend : Node.js, php symfony.
    Base de données : MongoDB ou PostgreSQL, solution open source selon les besoins de structure.
    Authentification : JWT ou OAuth pour la sécurité des sessions.

6. Plan de développement

    Phases du projet :
        Phase de conception : Wireframes, maquettes, validation du design.
        Phase de développement : Mise en place de l’architecture de base, développement itératif des fonctionnalités.
        Phase de test : Tests unitaires, tests d’intégration, tests d’acceptation par les utilisateurs.
        Phase de déploiement : Mise en production, formation des utilisateurs.
    Méthodologie : Agile pour une meilleure réactivité et adaptation.

7. Budget et ressources
    Mongulu étant une association a but non lucratif, on avancera avec les ressources disponibles.
    Estimation du coût : Développeurs, designers, frais de serveur.
    Ressources nécessaires : Personnel technique (développeurs, designers), infrastructure (serveurs, outils de développement).

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by billmetangmo** [comment]
CI/CD
- Preview environment ( env par branche avec main comme branche  qui déploie en production)
- Configuration Iac Google Cloud Run

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by Tchepga** [comment]
Chama est une application web conçue pour améliorer la communication et la gestion des associations étudiantes camerounaises. Cette solution tout-en-un est à la fois fiable, facile à utiliser, paramétrable et économique. Chama vise à offrir une plateforme générique couvrant toutes les fonctionnalités essentielles pour une association.

Objectifs du Projet

Objectif principal : Faciliter la gestion des associations étudiantes camerounaises à travers un site web complet et intuitif.

Objectifs spécifiques :

Gestion d'utilisateurs : Inscription, gestion de profils et droits d'accès spécifiques.
Gestion d'événements : Création, modification, inscription et archivage des événements.
Système de publication : Diffusion d'annonces, de nouvelles et d'articles.
Personnalisation : Adaptation de l'interface aux couleurs et logos de l'association, avec possibilité de modifier la description, les informations de contact et la galerie d'images.

Exigences Fonctionnelles

Utilisateurs : Différents types d'utilisateurs tels que l'administrateur, le membre de l'association et le visiteur, avec des fonctionnalités adaptées à chaque profil.
Événements : Une interface pour ajouter, modifier ou supprimer des événements, ainsi qu'un calendrier pour visualiser les événements.
Publications et Archives : Un système de gestion de contenu pour gérer les articles, les annonces, et un système d'archivage pour les contenus anciens.
Configuration et Personnalisation : Interface pour la modification du logo, de la description de l’association et des informations de contact.
Exigences Non Fonctionnelles

Performance : Réactivité du site et capacité à gérer un nombre élevé de visiteurs simultanément.
Sécurité : Gestion sécurisée des accès et protection des données personnelles.
Compatibilité : Support des différents navigateurs web et appareils mobiles.
Accessibilité : Conformité aux standards d'accessibilité web et design responsive.
Technologies à Utiliser

Frontend : Utilisation de React pour le développement de composants dynamiques.
Backend : CMS headless Directus pour la gestion facile et flexible du contenu.
Base de Données : MongoDB ou PostgreSQL, selon les besoins en termes de structure de données.
Authentification : Utilisation de JWT ou OAuth pour sécuriser les sessions des utilisateurs.
Plan de Développement

Phase de Conception : Création de wireframes, maquettes et validation du design.
Phase de Développement : Mise en place de l’architecture de base et développement itératif des fonctionnalités en intégrant Directus et React.
Phase de Test : Réalisation de tests unitaires, d’intégration et d’acceptation par les utilisateurs.
Phase de Déploiement : Mise en production et formation des utilisateurs finaux.
Méthodologie : Adoption de l'approche Agile pour une meilleure adaptabilité et réactivité aux besoins changeants.
Budget et Ressources

L'association Mongulu, à but non lucratif, utilisera les ressources disponibles pour avancer sur le projet. Les coûts sont estimés pour couvrir les développeurs, designers, et les frais de serveur, avec une équipe composée de personnel technique qualifié et une infrastructure adaptée aux besoins du projet.
