### ISSUE TITLE
Mettre en place l'environnement CI/CD

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#15]
Je voudrais un environnement de déploiement de l'application chama. Il sera basé sur l'application directus et reactjs qui permet de choisir sa base de données.

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by billmetangmo** [comment]
J'ai utillisé aws amplify pour déployer le code en le liant à ce repository donc ça devrait être le cas. Je vais faire un petit test.

**Comment by billmetangmo** [comment]
ça fonctionne https://github.com/mongulu-cm/chama/pull/19 . Je ferme l'issue @Tchepga
