### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#16]
Site web static basé sur les retours de l'aci. 
admin projet et event.
La v1 s'inspire de http://www.compagniedumessage.fr/

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue
