### ISSUE TITLE
création du footer

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#17]
https://www.loom.com/share/6015c69ef999401a9f73e0dc3108ecf0?sid=d86dacb2-771d-46dc-adba-e9eb494d7792

### Objective:

To create a footer component for a website that aligns with the design requirements and includes necessary information.

### Key Steps:

1. **Design Reproduction:**

   - Reproduce the footer design with the same information as provided.
   - Ensure the dimensions are in line with the design requirements.

2. **Component Creation:**

   - Create a new component for the footer.
   - Include the necessary text content.

3. **Styling:**

   - Use CSS classes to style the footer component.
   - Add generic classes for managing component properties.

4. **Data Injection:**

   - Inject data into the footer component.
   - Ensure the data is displayed correctly.

5. **External Libraries:**

   - Include any necessary external libraries for styling.
   - Utilize flexbox for alignment and responsiveness.

### Cautionary Notes:

- Pay attention to the design details and dimensions provided.
- Double-check data injection to ensure accuracy.
- Test responsiveness on different devices.

### Tips for Efficiency:

- Follow the design closely to maintain consistency.
- Use external resources for CSS alignment queries.
- Seek clarification if unsure about any design elements.

from loom

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue
