### ISSUE TITLE
ajouter carousel

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#20]
Mettre en place un carousel pour scroller les images

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.
