### ISSUE TITLE
Menu responsibe (mobile)

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#22]
Mettre en place le menu pour le mobile. Possiblité de faire plusieurs différents menu

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by billmetangmo** [comment]
Fait par @Tchepga
