### ISSUE TITLE
mettre en  place le système d'adhesion

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#27]
utiliser l'api de hello assos https://api.helloasso.com/v5/swagger/index.html
https://www.helloasso.com/outils/checkout

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by billmetangmo** [comment]
https://mui.com/

**Comment by billmetangmo** [comment]
- Onglet adhésion en 3ème dans le menu
- cliquer dessus 3 items: Pourquoi ahérer, adhérer, faire un don

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by billmetangmo** [comment]
On a le choix entre 3 aperçus:
- https://www.helloasso.com/associations/collectif-mongulu/adhesions/formulaire-ahesion/widget-bouton
- https://www.helloasso.com/associations/collectif-mongulu/adhesions/formulaire-ahesion/widget-vignette
- https://www.helloasso.com/associations/collectif-mongulu/adhesions/formulaire-ahesion/widget

**Comment by billmetangmo** [comment]
https://dev.helloasso.com/docs/environnements-production-et-sandbox-test

**Comment by billmetangmo** [comment]
SDK supporté ( SDK python): https://github.com/orgs/HelloAsso/repositories
Possibilité de créer les autres SDK à partir de fern et pingé helloasso: https://github.com/orgs/HelloAsso/repositories

**Comment by billmetangmo** [comment]
Il faut au préalabale que l'association:
- ait un compte helloasso
- créer une page d'adhesion
- ajoute l'url de la page d'adhésion dans directus
- ajoute comme administrateur

**Comment by Tchepga** [comment]
Je pense qu'il faudrait ajouter une section aide dans chama pour rappeler les différentes étapes pour l'adhesion cela

**Comment by Tchepga** [comment]
HelloAsso donne il la possibilité de paramètre le texte à afficher ?
