### ISSUE TITLE
Rendre le menu plus dynamique

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#28]
ajouter un hover sur les items du menu pour changer d'état lorsque la souris se trouve sur un item du menu

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.
