### ISSUE TITLE
migrer le contenu de les évenèments de l'ancien site aci vers le v1 mongulu

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#36]

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by billmetangmo** [comment]
Portage de tous les events sauf les assemblées générales. Faudrait-il rajouter un onglet documents ?

**Comment by billmetangmo** [comment]
Il me reste qu'à faire que slider ou le scroll infini prenne les events en partant du plus récent

**Comment by billmetangmo** [comment]
https://docs.directus.io/reference/query.html#sort
