### ISSUE TITLE
Ajouter les galeries dans les évènements et les projets

### ISSUE THREAD

**Issue by Tchepga** [mongulu-cm/chama#37]
les projets et les évènements peuvent avoir plusieurs images d'illustrations. Elles doivent s'afficher à la fin ce ceux ci et être scrollable s'il y en a plusieurs

**Comment by fabiolatagne97** [comment]
@Tchepga l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by fabiolatagne97** [comment]
@Tchepga merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.
